### ISSUE TITLE
pm이 여럿일 수 있어요. 어떻게 생각하나요?

### ISSUE THREAD

**Issue by khw7096** [studio2l/roi#1]
https://github.com/studio2l/roi/blob/db3b8bd12d45055201cbcc4b5544dc56e9e7615e/project.go#L24

**Comment by kybin** [comment]
아무 생각이 없어요.. 어떻게 해야 되죠?

**Comment by khw7096** [comment]
그러게요!!

**Comment by khw7096** [comment]
규모상 중요한게 아니니 나중에 바꿀까요?

**Comment by kybin** [comment]
VFXProducer 와 VFXManagers 로 변경하면 어떨까요?

**Comment by khw7096** [comment]
조직은 PD, PM으로 구분되어있어요? 전 잘 몰라서..

**Comment by kybin** [comment]
현재는 한분이 하고 있지만 전에는 그렇게 구분해서 작업하긴 했던 것 같아요

**Comment by khw7096** [comment]
일단 현재 상황이 맞추는것으로 하는게 좋을것 같아요.(입력칸이 생기는건 결국, 입력 권한이 생기니까요.)

**Comment by kybin** [comment]
@kaycho PM과 관련해서 어떤 구조를 가지면 좋을지 의견을 듣고 싶어요.

**Comment by kaycho** [comment]
입력되는 정보로 프로젝트 정보를 입력할 수 있는 권한도 컨트롤할 예정이신가요?

**Comment by kaycho** [comment]
여러명 등록할 수 있는 구조가 좋을 것 같습니다.
VFXManagers 보다는 VFXManagement 로 되어 있는게 PA가 경우를 포함할 수 있을 것 같습니다.

**Comment by kybin** [comment]
생각하시는 PM과 PA의 차이가 뭐가 있나요? 그리고 그건 roi에 어떻게 적용될까요?

**Comment by kybin** [comment]
아 제가 이전 글을 이해를 잘 못했었네요. 
일단 지금은 프로젝트 내의 다른 항목들과 비슷한 형식으로 했으면 좋겠습니다. 
'사람들'이라는 느낌이 드는 다른 단어가 있을까요?

**Comment by kybin** [comment]
아, 제 생각은 어시나 코디네이터도 Managers안에 포함시키는 거였습니다. 결국 같은 역할이라고 봤거든요.

**Comment by kaycho** [comment]
같은 생각입니다!
management 라는 단어가 들어가면 될것 같습니다.

**Comment by kybin** [comment]
완료: 392b089f3646904bac3c3afcc60bf024b547503e
