### ISSUE TITLE
ordMap 제거

### ISSUE THREAD

**Issue by kybin** [studio2l/roi#109]
ordMap은 어쩌면 너무 영리하게 처리하려고 했던 내 실수인 듯 하다.

덜 영리해도 더 명확한 코드를 작성하고 싶다.

**Comment by khw7096** [comment]
전 이 부분은 찬성해요!
언어에서 기본적으로 지원하는 자료구조 이외에 사용자가 특이한 자료구조를 만들어서 값을 리턴하게 만드는것이
한창 개발진행중일 때 좋을까 속으로 고민했었거든요.

**Comment by kybin** [comment]
이건 좀 다른 얘기지만 ordmap은 특이한 자료구조는 아니라고 생각해요.  제가 가장 좋아하는 자료구조의 형태입니다. 
실제로 현재 파이썬의 dict는 순서를 가지는 형태로 재구현되었구요. 언젠가는 Go에도 이 형식이 기본으로 들어올거라고 생각합니다.

**Comment by kybin** [comment]
그럼에도 불구하고 현재 기본적으로 지원하지 않는 형식을 굳이 만들어 쓴 건 분명히 코드의 복잡도를 높이는 방향으로 작용했다고 생각합니다.

**Comment by khw7096** [comment]
일단 이슈로 있어서 전 이 링크를 봤었어요.

https://golanglibs.com/search?q=ordered+map&sort=top&page=1
