### ISSUE TITLE
Output struct에 File 은.. Files가 되는것이 더 좋을 것같아요.

### ISSUE THREAD

**Issue by khw7096** [studio2l/roi#110]
매치무브 작업을 가상의 예로 들면..
3D 이퀄라이저로 작업을 하면 생성되는 파일이..
- 3eq파일
- 언디스토션 플레이트 경로
- 뉴크파일
- 마야파일

일테니까요.

**Comment by kybin** [comment]
미처 생각하지 못했네요. 고마워요.
