### ISSUE TITLE
GUI: 날짜 선택 창 구현 필요

### ISSUE THREAD

**Issue by kybin** [studio2l/roi#187]
경식씨 아시는 방법있으면 좀 남겨주세요~

**Comment by kaycho** [comment]
semantic-ui에는 Calendar 기능을 지원하지 않아서 서치했었습니다.
아래 3가지 방법이 있습니다. 
1. [semantic-ui-calendar](https://github.com/mdehoog/Semantic-UI-Calendar)
2. [jquery 사용](https://codepen.io/SaadRegal/pen/ZOABQr)
3. [fomantic-ui](https://github.com/fomantic/Fomantic-UI)

**Comment by kybin** [comment]
아아. 폰이라 다 살펴보지는 못했지만 룩앤필이 비슷할 첫번째로 갈까 싶네요. 혹시 더 선호하는 방법이 있으신가요?

**Comment by kaycho** [comment]
3가지 방법 모두 semantic-ui와 동일한 룩앤필을 유지하고 있습니다.

**Comment by kybin** [comment]
어느쪽이든 저는 크게 상관없으니 경식씨가 결정해주세요~

**Comment by kaycho** [comment]
jquery사용해서 구현하는게 수정하거나 기능을 추가하는데 나을것 같아 먼저 적용할 것 같습니다.

**Comment by kybin** [comment]
네 예제로 혹시 한 군데 만들어주실수 있나요? 전체 적용하는건 제가 붙여넣을게요.

**Comment by kaycho** [comment]
최근 버전으로 로이를 확인할 수 없어서 코드만 올립니다.
profile.html 에 생일 정보를 입력한다고 가정한 내용입니다.

```
<div class="field"><label>생일</label>
	<div class="ui calendar" id="birthday">
		<div class="ui input left icon">
			<i class="calendar icon"></i><input type="text" placeholder="날짜 선택">
		</div>
	</div>
	<script>
	//날짜만 선택, 날짜와 시간을 함께 선택하려면 {type:'date'}를 삭제합니다.
	$('#birthday').calendar({
		type: 'date'
	});
	</script>
</div>

**Comment by kybin** [comment]
감사합니다. 이걸로 잘 붙여넣어 볼게요 ㅎㅎㅎ

> 최근 버전으로 로이를 확인할 수 없어서

헉 왜죠?

**Comment by kybin** [comment]
제 자리에서는 잘 안되네요. ㅠㅠ. 이걸 쓰기위해 jquery 모듈 같은게 추가적으로 설치되어야 하나요?

**Comment by kaycho** [comment]
tmpl/head.html 에 포함되어있습니다.

확인은 하고 올린 코드에요.

제가 로이 다시 설치해보고 pr을 올리도록 할게요~

**Comment by kybin** [comment]
네~ 혹시 로이가 실행 안되면 뭐 때문에 안 되는지 좀 알려주세요.

**Comment by kaycho** [comment]
다른 방식으로 구현해야할 때 새로운 이슈를 등록하겠습니다.
