### ISSUE TITLE
각 항목에 어떤 상태가 있어야 하는지와 항목간 인터랙션 논의 필요

### ISSUE THREAD

**Issue by kybin** [studio2l/roi#230]
다음 각 항목들은 모두 상태에 대한 정의가 필요합니다.

- 프로젝트
- 샷
- 태스크
- ~버전~

현재는 제가 그냥 생각나는 상태들을 등록시켜 놓았지만, @kaycho 님의 의견이 필요합니다.

**Comment by kaycho** [comment]
버전은 상태를 항목으로 가지지 않고 아래 처럼 속한  샷과 태스크의 상태를 따라가는게 맞는 것 같습니다.
- 샷의 버전 (comp task 버전과 연동) (ex: shot_version / retake)
- 태스크의 버전 (ex : task_version / wip)

현재 사용 중인 상태들을 기준으로 더 세분화 혹은 변경할지 보면 될것 같습니다.
내용을 추가로 등록하겠습니다.

**Comment by kybin** [comment]
현재 각 항목은 가장 단순한 형태의 상태를 가집니다. 버전은 상태를 가지지 않으며, 태스크의 속성으로 통합되어있습니다. 이 형태가 효율적인지는 (적어도 문제가 없는지는) 실제 사용하면서 평가해봐야 할 것 같습니다.
