### ISSUE TITLE
프로젝트의 타입 정보

### ISSUE THREAD

**Issue by kaycho** [studio2l/roi#242]
프로젝트의 타입 정보 입력이 필요합니다.
프로젝트의 정보를 확인시 타입 정보로 미리 파악할 수 있는 내용들이 있습니다.

영화, 드라마, CF 등 분야 혹은 3D 작업 유무 등 작업 형태에 따라 타입을 정리해 입력합니다.

미리 타입정보를 정의하지 않고 전체 설정에서 입력 가능한 타입을 리스트형태로 설정 할 수 있으면 좋을 것 같습니다. (ex: film, drama, cf 혹은 A-type, B-type)

**Comment by kybin** [comment]
좋습니다 사이트 설정에 넣도록 할게요.

한가지 A-Type이 의미하는 바가 뭔지 잘 모르겠네요. 드라마랑 같은건가요?

**Comment by kaycho** [comment]
용어가 아니라 회사마다 정의한 타입명을 입력할 수 있게 한다는 의미로 임의로 넣은 단어 입니다.

**Comment by kybin** [comment]
네~

**Comment by psh845** [comment]
shotgun project info has Color Space, Projection Resolution, Delivery Resolution, Delivery Format 

Please include the that item, if possible.

**Comment by kybin** [comment]
thank you. by the way, why do you use english?

**Comment by psh845** [comment]
I want to look like a foreigner. :)

**Comment by khw7096** [comment]
The review became interesting because psh845 wrote it in English. ha ha!!

**Comment by kybin** [comment]
현재는 타입 정보가 쇼에 들어가있다.
