### ISSUE TITLE
$ is not defined 에러

### ISSUE THREAD

**Issue by kybin** [studio2l/roi#248]
파이어폭스의 디버그 콘솔을 열어서 확인하면 모든 페이지에서 아래 에러 메시지가 뜬다.

```
ReferenceError: $ is not defined[Learn More] roi.js:2:1
<anonymous>
https://localhost/static/roi.js:2:1
```

jquery가 선언되기전에 $를 사용해서 그런 것 같다. (roi.js에는 현재 `$("add-menu").dropdown();` 같은 jquery를 이용한 구문이 존재한다.)
재밌는 점은 에러가 나지만 드롭다운은 작동한다는 것이다.

**Comment by kaycho** [comment]
https://github.com/studio2l/roi/pull/251#issuecomment-468985133

**Comment by kaycho** [comment]
이 이슈는 해결된것 같습니다.

**Comment by kybin** [comment]
네 닫을게요.
