### ISSUE TITLE
프로젝트 컬러 스페이스, 프로젝트 아웃풋 사이즈, 딜리버리 사이즈, 딜리버리 포맷 설정 필요. - 박상호

### ISSUE THREAD

**Issue by kybin** [studio2l/roi#269]
프로젝트에도 태그가 있어 태그로 설정하면 어떨까도 생각해봅니다.

프로젝션 사이즈는 뭔가요?

**Comment by psh845** [comment]
프로젝트 사인즈 인거 같아요

**Comment by kybin** [comment]
네, 나중에 참고할게요. 현재는 elo를 만들고 있어서 조금 뜸해요.

**Comment by kybin** [comment]
이제는 커스텀 속성이 추가되어, 각 사이트(스튜디오)에서 필요한 원하는 속성을 넣어서 쓰면 됩니다!
