### ISSUE TITLE
Ordmap을 사용하는 이유가 뭐예요?

### ISSUE THREAD

**Issue by khw7096** [studio2l/roi#27]
주석에 없어서 이슈에 남겨요.

**Comment by kybin** [comment]
엑셀의 한 열과 가장 비슷한 형식이기 때문이에요.

엑셀의 열은 특정 항목(키)에 대한 값 들이고, 순서대로 정렬되어 있잖아요.

**Comment by khw7096** [comment]
이해했어요. 이 이슈를 닫을께요.
