### ISSUE TITLE
book 자료구조를 tag로 바꾸기

### ISSUE THREAD

**Issue by khw7096** [studio2l/roi#28]
roi가 vfx, 애니메이션, 게임등에 범용으로 쓰이길 바라는 마음에.. 꼭 필요한 데이터 구조를 제외한 나머지 구조는 태그를 활용하는 방안이 어떨까 해서 생각하는 제안이예요.

**Comment by kybin** [comment]
흠.. 글쎄요 저는 크게 상관없을것 같긴한데, 경식씨의 의견이 궁금하네요

**Comment by kaycho** [comment]
저도 태그를 활용하는 방향이 좋습니다. 동시에 태그의 사용 가이드?가 필요합니다. 매우 창의적으로 태그를 활용하는 유저들이 많더라구요.

**Comment by kybin** [comment]
제안 수락 된 것으로 하겠습니다. 앞으로 이 이슈는 실제로 전환이 일어날 때까지 살려두겠습니다.

**Comment by khw7096** [comment]
오 마이 갓~!! 제안이 받아들여지다니!!!! 감격!! 폭풍 오열 눈물!!

**Comment by kybin** [comment]
제가 진행할게요.
