### ISSUE TITLE
버전을 문자열로 변경

### ISSUE THREAD

**Issue by kybin** [studio2l/roi#317]
현재는 Version이 정수이다. 하지만 2L 내에서는  'v'와 패딩을 붙여 v001 처럼 사용한다. 또 다른 스튜디오에서는 0.0.1 처럼 버전을 사용할 수도 있다. 어떤 형식이든 지원할 수 있도록 버전을 문자열로 변경할 생각이다.

**Comment by khw7096** [comment]
이건 꽤나 좋은 방법이네요. csi도 버전은 정수를 사용하고 있거든요.

**Comment by kybin** [comment]
아직 본격적으로 써보지는 못했지만 괜찮은 방법인것 같아요
