### ISSUE TITLE
브라우저 화면의 글씨가 너무 작아요.

### ISSUE THREAD

**Issue by khw7096** [studio2l/roi#35]
제 시각에서는 브라우져에서 150% 키웠을 때 자연스러운 느낌이 있어요.

**Comment by kybin** [comment]
좋은 생각입니다. 경식씨에게로 패스.

**Comment by kaycho** [comment]
참고하도록 하겠습니다.

**Comment by kybin** [comment]
한가지 고려해야 할 사항은 일반적인 스튜디오 모니터는 노트북보다는 훨씬 크다는 것입니다.
두 군데 모두에서 잘 보이면 가장 좋겠지요.

**Comment by kybin** [comment]
충분히 논의 되었다고 판단하고 닫습니다.
