### ISSUE TITLE
macOS에서 실행시 에러

### ISSUE THREAD

**Issue by khw7096** [studio2l/roi#381]
![image](https://user-images.githubusercontent.com/1149996/70391288-ca11fa80-1a16-11ea-97c0-f814b48f6804.png)

**Comment by kybin** [comment]
db는 cockroachdb였나요?

**Comment by kybin** [comment]
업데이트했으니 다시 한번 실행해 줄수 있어요?

**Comment by khw7096** [comment]
하잇~! 집에서 또 해볼께용~!

**Comment by khw7096** [comment]
![image](https://user-images.githubusercontent.com/1149996/71310297-ea4daa80-2455-11ea-94c0-64ae149a984c.png)

12월 22일 현재 아직도 같은 에러이긴해요.

**Comment by kybin** [comment]
이제 코드 내에 ON CONFLICT라는 구문이 없는데 이상하네요. 제가 맥이 없어 이 에러메시지만 가지고는 어떻게 해야 할 지 모르겠네요. 혹시 조금 더 자세한 정보를 얻게 된다면 알려주세요.

**Comment by khw7096** [comment]
네

**Comment by kybin** [comment]
추가 정보가 없은지 너무 오래되어 닫습니다. 혹시 다음에 또 실행되지 않으면 새 이슈로 남겨주세요!
