### ISSUE TITLE
문자열 필드를 []string으로 분리할 때 콤마(,)가 아닌 공백을 사용한다.

### ISSUE THREAD

**Issue by kybin** [studio2l/roi#386]
현재는 text 필드를 []string으로 만들어야 할 때 그 구분자로 콤마를 사용하는데 공백으로 변경하려한다.

가장 큰 이유는 리드 설정부분에 `mod:user,user fx:user,user`처럼  필드에 더 작은 구분이 필요할 때
공백을 큰 구분자로 쓰는게 더 나아보이기 때문이다.

만약 콤마를 큰 구분자로 사용하면 `mod:user user, fx:user user`처럼 작성해야 하는데 위와 비교해서 덜 명확한 느낌이다.

**Comment by baesy0** [comment]
동의!

**Comment by kybin** [comment]
고민해보았는데, 변경하지 않기로 하였습니다.
가장 중요한 이유는 한 줄 안에 많은 정보를 담아 보았는데 어떤 방식이든 가독성이 떨어져 여러 줄을 사용할수 있는 textarea 태그를 이용해야 할 듯 합니다.
그러면 어차피 새로운 문자열 파싱을 추가해야 하기 때문에 이 변경으로 얻을 수 있는 이득이 적습니다.
적은 양의 정보는 콤마가 더 명확히 분리되어 보이기도 하고요.
