### ISSUE TITLE
roi의 로그 및 에러 메시지를 한글화 해야 할까요?

### ISSUE THREAD

**Issue by kybin** [studio2l/roi#40]
roi는 한국 VFX 산업에 도움 줄 목적으로 만들어지고 있습니다.
그래서 모든 주석도 한글화 하고 있습니다. 
하지만 아직 로그나 에러 메시지는 영어로 출력되고 있습니다.
이 부분을 한글화 하면 더 좋을지에 대한 여러분의 생각이 궁금합니다.

**Comment by khw7096** [comment]
지금의 구조를 놔두고 나중에 많은 언어를 지원할 수 있게 구조만 만들어두는건 어때요?

**Comment by kybin** [comment]
앞으로 오랜시간 동안 하나의 언어를 사용하게 될 텐데 그 기간 동안 영어를 쓸 것인지 묻는거에요.

한웅씨의 의견은 영어를 그냥 쓰자는 거죠? 이유는 뭐에요?

**Comment by kaycho** [comment]
한글화 하는것에 찬성합니다.
한글 사용이 사용자, 개발자 여러 부분에서 도움이 될 것 같습니다.

**Comment by khw7096** [comment]
@kybin 영어,한국어를 같이 쓰자는 의견에 대한 이유는 

roi는 한국 VFX 산업에 도움 줄 목적이라 목적이 굉장히 크기 때문에 사용자들이 영어를 지원해달라고 요청할까봐요.

**Comment by kybin** [comment]
@khw7096 이 문장은 이해를 하지 못했어요. 왜 영어를 지원해 달라고 요청할 것 같은거에요?

**Comment by khw7096** [comment]
Csi를 만들때 비슷한 경험이 있어서요. 벤쿠버 분이 한국 사람이었는데 고용한 사람이 영어권 사람이었어서요~

**Comment by kaycho** [comment]
@khw7096 일반 유저 를 위한 프론트엔드단에서의 다국어 기능 요청 이었나요?

**Comment by khw7096** [comment]
@kaycho 네 전 업무하면서 벤쿠버에서..

**Comment by kybin** [comment]
일단 한국어로 출력 및 로깅 하는 것은 보류하겠습니다.

Go의 스탠다드 라이브러리나 js 라이브러리가 이미 영어로 에러등을 출력하는데, 영문과 한글이 섞이면 사용자에게 혼란을 줄 수도 있을것 같습니다.

한글 로깅이 필요하다고 생각하시는 분이 있으면 새 이슈로 생성해주세요.

**Comment by khw7096** [comment]
둘중에 선택한다면 영어에 한표.
