### ISSUE TITLE
bakego 데이터와 실제 파일이 정확히 같은지를 자동으로 테스트 할 수 있는 메커니즘 필요.

### ISSUE THREAD

**Issue by kybin** [studio2l/roi#44]
개발이 진행됨에 따라 스태틱 파일을 고칠때는 항상 bakego를 실행시켜주어야 하지만,
깜빡할 수 있는 여지가 많다.

**Comment by khw7096** [comment]
javascript같은 라이브러리는 어떻게 해야해요?

**Comment by kybin** [comment]
이제 ci에서 go test를 통해 bake를 깜빡했는지 체크할 수 있다.
