### ISSUE TITLE
show 또는 project 둘 중 하나로 정하기.

### ISSUE THREAD

**Issue by kybin** [studio2l/roi#57]
현재 로이는 각 프로젝트를 project라고 부르고 있는데 사용하고 있는데, 

show라고 바꾸는게 나을까요? 아니면 그대로 둘까요?

**Comment by kaycho** [comment]
Show 라고 해야할 특별한 이유가 없다면 Project가 가장 일반적이고 다양한 분야에 통용될 수 있다고 생각해요. 전 그대로 project로 사용되면 좋겠습니다.

**Comment by kybin** [comment]
네, 한웅씨 의견도 들어볼게요.

**Comment by kybin** [comment]
그렇다면 전 제 맘대로, 프로젝트로 하겠습니다.

**Comment by kybin** [comment]
던.
