### ISSUE TITLE
현황을 보여주는 페이지에서 차트 구현이 필요하다.

### ISSUE THREAD

**Issue by kaycho** [studio2l/roi#58]
Dashboard 형태의 페이지에서 차트 구현이 필요하다.

chartjs를 고려하고 있다. ( https://www.chartjs.org/ )

**Comment by kybin** [comment]
차트 라이브러리 용량은 얼마나 돼요? 저는 최대한 가벼운 라이브러리를 사용했으면 하는 생각이 있어요.

**Comment by leycap** [comment]
동의합니다.

**Comment by kaycho** [comment]
같은 생각으로 chartjs를 고려하고 있습니다. 필요한 차트의 코드만 사용하면 100KB 아래로 예상됩니다. 더 적은 용량으로 가능한 라이브러리가 있다면 추천 바랍니다~

**Comment by kybin** [comment]
몰라요 ㅋㅋ

**Comment by kaycho** [comment]
^^ 일단 이슈 달아 놓고 좀더 서치 해보려구요~

**Comment by kybin** [comment]
현재는 기본적인 기능에 집중하고 있어요. 비주얼라이징은 추후 다시 생각해볼게요!
