### ISSUE TITLE
제안: 샷의 tag에 '키:값' 형식 허용

### ISSUE THREAD

**Issue by kybin** [studio2l/roi#62]
현재 태그는 그냥 값의 나열입니다. 예를 들어 

CG0010의 태그는 1권,로이킴,커피
CG0020의 태그는 1권,용빈킴,홍차

라고 했을 때, 이 태그의 카테고리는 존재하지 않습니다.

각 태그의 카테고리를 더 명확하게 설정하려면, 이렇게 할 수 있을 겁니다.

CG0010 -> 권:1권,연기자:로이킴,음료:커피
CG0020 -> 권:1권,연기자:용빈킴,음료:홍차

제가 제안하는 것은 이 둘을 혼용하자는 것입니다.

CG0010 -> 권:1권,연기자:로이킴,커피
CG0020 -> 권:2권,연기자:용빈킴,홍차

이렇게 하면 카테고리를 가지는 태그와, 가지지 않는 태그를 생성할 수 있습니다.

왜 태그에 카테고리가 필요하다고 느끼냐면, 경식씨의 제안처럼 각 사이트마다 별도의 정보를 넣고, 그 정보를 웹 상에서 추가적으로 표현해 주기 위해서는, 그 항목의 키(카테고리) 정보가 필요하기 때문입니다.

이를 그림으로 그리면

| 이름 | 씬 | ... | 권(추가된 항목) | 연기자 (추가된 항목) |
| ------ | --- | --- | --------------------- | ---------------------------- |
| CG0010| A|  | 1권 | 로이킴 |
| CG0010| A|  | 1권 | 용빈킴 |

태그를 활용하는 방식은 Shot에 필드를 만들지 않고 샷 테이블에 항목을 추가할 수 있는 방법입니다.

## 대안

또는 Shot에 CustomFields 라는 필드를 추가하여 같은 기능을 구현 할 수 있습니다.
한편으로는 더 명확하지만, Shot의 복잡도가 증가한다는 점에서 꺼려집니다.

또 사이트마다의 추가 설정을 허용하지 않는것도 하나의 방법입니다.
이 방법은 불편함을 야기할 수는 있지만 프로그램의 복잡성이 증가하지 않습니다. 

여러분의 생각은 어떤가요? 혹은 더 나은 방법이 생각나면 제안 부탁드립니다.

**Comment by khw7096** [comment]
저는 그냥 문자열의 나열이 좋다고 생각해요. 전 페이스북이나, 인스타, 유투브 등의 태그 개념을 좋아하기 때문이예요. 개인적인 생각입니다.

**Comment by kybin** [comment]
정확히 어떤 의견인지 모르겠네요. 다음 중 어떤것과 가장 가까운 생각인가요?

1. 태그에 키:값을 추가한다.
2. Shot에 CustomField 필드를 만든다.
3. 아무것도 하지않고, 사이트의 추가 설정을 허용하지 않는다.
4. 다른 의견

**Comment by khw7096** [comment]
4번 의견인것 같아요.

**Comment by kybin** [comment]
4번은 해석하자면 아무것도 하지않지만, 사이트의 추가 설정을 허용한다인데.. 이 의견이라는 건가요?

**Comment by kaycho** [comment]
1번 선택하고 싶습니다.

**Comment by kybin** [comment]
이 부분에 대해서는 생각이 나뉘니 일단 구현해 보는 것으로 하겠습니다.
