### ISSUE TITLE
소스와 샷의 상관관계 정확히 파악하기.

### ISSUE THREAD

**Issue by kybin** [studio2l/roi#7]
한웅씨가 본다면, 설명 부탁해요.

**Comment by khw7096** [comment]
샷에는 작업플레이트 포함, 여러 소스가 들어올 수 있어요.

- shot
    - plate1 < 어떤 소스가 master plate 인지 설정할 필요가 있음.
    - plate2
    - plate3
    - plate4
    - 또는 plate2 + plate3을 섞은 플레이트가 master plate가 될지도..

**Comment by kaycho** [comment]
- org, src (혹은 base, source) 로 master plate와 element plate를 구분합니다.
- master plate 변경시 아티스트에게 바로 전달 될 수 있어야 합니다.
- 편집 변경으로 편집점이 달라지거나 길이가 달라질 수 있습니다.
- element plate의 경우는 확정되지 않고 여러가지 버전이 존재하기도 합니다. 
- element plate는 해당 샷의 편집 길이와 전혀 다를 수 있습니다.
- element plate는 합성 배경, 특수효과, 프롭 촬영 등을 의미합니다.

생각나는대로 놓습니다.

**Comment by khw7096** [comment]
lazypic 경로 규칙은 아래와 같아요. 저도 추가적으로 작성해요.

‘’’
/show/circle/shot/foo/0010/plate/v001
/show/circle/shot/foo/0010/src/v001
/show/circle/shot/foo/0010/ref/v001
‘’’

**Comment by kybin** [comment]
어느 정도 소스와 샷에 대해서 파악한 것 같아요. 두 분 다 감사합니다.
