### ISSUE TITLE
샷 이름이 CG0001 에 대한 개인적인 생각.

### ISSUE THREAD

**Issue by khw7096** [studio2l/roi#75]
보통 EDL을 통해서 넘어오는 이름은 Scene, Cut으로 넘어옵니다.
```
037 131    V     K B      10:57:40:22 10:57:41:11 01:00:36:08 01:00:36:27
037 051    V     K O  000 01:07:39:05 01:07:39:24 01:00:36:08 01:00:36:27
```

037 이라고 불리는 부분이 아무래도 같은 씬으로 묶일 수 있는 소지가 많습니다.(카메라가 촬영되면 계속 이어서 찍힐 테니까요.)

현대의 대부분 툴은 EDL을 저장할 때 CMX3600 포멧을 사용해요.
CMX3600 포멧은 8자리, A-Z 그리고 0-9 문자만 사용하며 다른 문자 자체는 허용하지 않습니다.

> 다빈치 리졸브도 CMX3600을 사용합니다.

참고 : http://www.edlmax.com/EdlMaxHelp/Edl/maxguide.html

카페에서 이 문제로 토론한 적이 있어서 생각이 난김에 정보를 남깁니다.

결론 : 
- {seq:FOO, shot:0010} 을 사용하자.
- 위 정보와 같은 EDL의 쌍 구조이며, 알파벳 대문자와 숫자로만 이루어져있다.
- 나중에 시간이 없거나 회사가 오로지 DB로 돌아가기 시작하면 EDL의 Reel 네임을 그대로 DB에 넣더라도 문제는 없을것입니다.

**Comment by kybin** [comment]
시퀀스와 씬에 대한 혼동이 오긴 하는데 그건 #76 에서 토론하시죠. 

일단 샷 이름은 프로젝트 전체를 통틀어 고유해야 할 것 같습니다. 그래야 db에서 불러올 때 복잡해지지 않습니다.

이름과 번호를 분리시키는 것이 방법일지도 모르겠습니다.

예를 들어 샷 안에 다음 정보가 저장되는 거죠.

이름: FOO0010
시퀀스: FOO
번호: 0010

이렇게 하는 것에 대해 어떻게 생각하세요?

**Comment by kybin** [comment]
> CMX3600 포멧은 8자리, A-Z 그리고 0-9 문자만 사용하며 다른 문자 자체는 허용하지 않습니다.

그 값이 여기서는 037 인가요?

**Comment by kaycho** [comment]
참고로 CG0001 은 PM팀에서 특별한 이유 없이, 전임자가 직전 프로젝트에 사용했던 방식을 적용한 샷네임 형태라고 합니다. 
제시하신 형태가 맞는 방향이라고 생각합니다.

**Comment by kybin** [comment]
샷 이름을 무엇으로 할지는 로이의 사용자가 결정할 내용이라고 생각합니다.

다만 샷 이름 규칙은 아래로 정하였습니다.
1. 영문자로 시작한다.
2. 그 이후에는 영문자, 언더바, 숫자 만 사용한다.

이미 그렇게 구현되어 있으니 일단 이 논의는 닫겠습니다. 혹시 동의하지 않으면 다시 열어주세요.
