### ISSUE TITLE
시퀀스, 씬의 개념 정리하기

### ISSUE THREAD

**Issue by kybin** [studio2l/roi#76]
현재 제게는 시퀀스와 씬의 개념이 명확하지 않습니다.

시퀀스는 무엇이고, 씬은 무엇인지, 그리고 우리는 언제 뭘 써야 하는지 생각이 있으신 분들은 여기에 답글 바랍니다.

**Comment by kaycho** [comment]
구글에서 "시퀀스 씬" 이라고 서치하면 가장 상단에 나오는 포스팅인데 설명이 잘 되어있는 듯 해서 링크합니다.
https://m.blog.naver.com/PostView.nhn?blogId=whiskerguy&logNo=70167693269&proxyReferer=https%3A%2F%2Fwww.google.com%2F

**Comment by kaycho** [comment]
위 링크는 영화 이론적인 설명이고 일반적으로는
릴(권) 단위로 전달 받고 시퀀스, 씬을 구분해서 전달 받지는 않습니다.
VFX작업 준비하면서 씬네임을 지정하고 필요에 따라 시퀀스도 지정합니다.
단, 외주를 받거나 특별한 프로젝트의 경우 샷네임까지 지정해서 받기도 합니다.

편집 순서 혹은 장면을 기준으로 씬을 나누고, 유사한 씬들을 시퀀스라는 단위로 묶어 줍니다.

---
seq001 (숲속 낮)
-    scene-001 (숲속 회상)
-    scene-007 (숲속 전투)
-    scene-010 (숲속 대화)

seq002 (숲속 밤)
-    scene-002 (숲속 회상)
-    scene-009 (숲속 전투)
-    scene-022 (숲속 대화)

---

카테고리라고 생각 가능할 것 같습니다.
- 시퀀스 > 씬 > 샷

그래서 VFX에서는 시퀀스와 씬의 경계가 모호하게 사용되는 것 같습니다.

씬 구분 가능한 기능은 필수적이고 시퀀스도 필요합니다.

씬이 필요한 이유는
동일 공간, 시간의 씬별로 팀, 아티스트별로 Assign해야 작업 효율이 높아지기 때문입니다.
샷이 적은 경우 씬을 사용하지 않을 수 있습니다.

**Comment by kaycho** [comment]
참고로 샷건에는 에피소드 구분을 지정 할 수 있습니다.

**Comment by kaycho** [comment]
에피소드가 추가로 있습니다. 시퀀스 상위개념으로요.
[SG Support 참고](https://support.shotgunsoftware.com/hc/en-us/articles/115000019414-How-does-the-Episode-entity-work-)

**Comment by khw7096** [comment]
픽사에서 사용하는 OpenTimelineIO는 이름(string)이 기본이고 사용자가 값을 추가할 수 있어요.
-https://opentimelineio.readthedocs.io/en/latest/tutorials/otio-file-format-specification.html#stack-1

![otio](https://user-images.githubusercontent.com/1149996/50449448-d4a0c480-096a-11e9-9237-3dbca89e613c.png)

집에서 테스트하는 OTIO view 테스트 이미지도 올려둘께요.

**Comment by kybin** [comment]
@kaycho  샷건에서는 씬을 사용하지 않는 것처럼 보이네요. 그런가요? 또한 자세한 정리 감사합니다.

**Comment by kybin** [comment]
@khw7096 어떤 점을 말하려는 건지 정확히 이해가 되지 않아서 조금만 더 자세히 알려줄래요?

**Comment by kaycho** [comment]
@kybin 선택적으로 사용합니다. 프로젝트마다 스키마 설정시 원하는데로 적용가능합니다.
필수적으로 사용해하는 것은 없습니다. OpenTimelineIO 처럼 필요시 사용자가 항목을 추가해서 사용합니다.

#30 에서 설명하려고 한것과  비슷한 개념입니다.

작업 샷이 적은 프로젝트에서는 Scene 항목 없이 스키마를 설정하고
작업 샷이 많은 프로젝트에서는 Sequence, Scene 모두 생성해서 구분하는 형태입니다.

우리는 태그로 이러한 부분을 커버하기로 했다고 알고 있습니다. #62

**Comment by khw7096** [comment]
픽사는 name 만써요. string 한개.

**Comment by kybin** [comment]
@khw7096 아 무슨 말인지 알았어요. 저 이미지가 클립이어서 이해하기 어려웠던 것 같아요.

**Comment by khw7096** [comment]
@kybin OTIO는 타임라인 > 트렉 > 시퀀스 > 클립 순이 크기의 개념같아요.

영화에서는 시퀀스 > 씬 > 샷 처럼요.

**Comment by kybin** [comment]
이제 시퀀스가 무엇인지 씬이 무엇인지 어느 정도는 이해했습니다.

그렇다면 저희는 프로젝트, 씬, 샷 + 태그 (에피소드, 시퀀스) 모델로 가는게 좋을까요?

**Comment by kaycho** [comment]
좋습니다. 그리고 이런 모델이라면

> 프로젝트, 샷 + 태그 (릴,에피소드,시퀀스,씬 등등)

형태도 가능 할것 같습니다.

**Comment by kybin** [comment]
한웅씨 생각은 어떤가요?

**Comment by kybin** [comment]
씬과 시퀀스에 대해서 충분한 토론을 했다고 판단해서 닫습니다.
