### ISSUE TITLE
OS 독립적인 자가 인증서 생성 방법 찾기

### ISSUE THREAD

**Issue by kybin** [studio2l/roi#77]
generate-self-signed-cert.sh는 리눅스에서만 사용가능하다.

**Comment by kaycho** [comment]
현재 roi에 적용된 generate-self-signed-cert.sh를 말씀하시는게 맞다면
윈도우에서도 사용가능 한듯한데요
다른 상황에서 리눅스에서만 사용가능하다고 하시는건가요?

**Comment by kybin** [comment]
오 그런가요. 생각해보니 윈도우즈에서도 GitBash를 사용하고, $GOROOT가 잡혀있다면 generate-self-signed-cert.sh 를 사용할 수 있겠네요. 하지만 역시 온전한 방법이라고 생각이 들지는 않아서요.

**Comment by kybin** [comment]
현재는 mkcert를 이용하는 방법으로 변경하였음.
