### ISSUE TITLE
semantic-ui 적용 스크린샷

### ISSUE THREAD

**Issue by kaycho** [studio2l/roi#85]
기존의 ui를 변경하고 추후 기능에 맞춰서 추가합니다.

PR전 스크린샷을 업로드할 예정입니다.
![roi_screenshot_181228](https://user-images.githubusercontent.com/33473665/50512164-f1a4d700-0ad3-11e9-8093-e2ffd231dba7.png)

**Comment by kybin** [comment]
각 PR마다 스크린샷을 올려주시면 참고할게요. 이 이슈는 닫습니다.
