### ISSUE TITLE
프로젝트에 Lut 경로 위치가 필요할까요?

### ISSUE THREAD

**Issue by kybin** [studio2l/roi#90]
현재 프로젝트에 Lut파일 정보가 있는데, 과연 필요한 것인지 의문이 들어서 질문해요. 

애초에 Lut정보가 들어간 이유는 기존 파이프라인 툴에는 이 정보가 있어서 들어가게 되었습니다.

**Comment by kaycho** [comment]
프로젝트마다 공통된 LUT을 가지고 작업을 하기 위해 정보를 담아 놓는것이 필요합니다.

**Comment by kybin** [comment]
그렇다면 LUT 하나가 아니라 두 개의 LUT이 필요하진 않나요?

1. 인풋 -> CG
2. CG -> 아웃풋

**Comment by kybin** [comment]
아. 알겠어요. 감사합니다.

**Comment by khw7096** [comment]
mov로 나가는 중간 컨펌데이터는 lut를 적용하지 않나요?

**Comment by kybin** [comment]
한웅씨 질문이 있었기에 다시 엽니다.

**Comment by kaycho** [comment]
중간 컨펌 데이터용 lut는 보통 어디서 결정하나요?
lut의 경로 정보는 하나여도 필요한 lut가 여러개라면 별도로 정보를 기록해도 될것 같습니다.

**Comment by khw7096** [comment]
@kaycho 클라이언트 측에서 고용한 슈퍼바이져가 중간 컨펌용 lut를 결정합니다.

**Comment by khw7096** [comment]
lut는 파일이기 때문에 1개 2개 같은 개념은 아니고 프로젝트마다 갯수 및 적용방법이 달라질듯해요. 회의를 통해서요.

**Comment by kybin** [comment]
인풋 Lut은 하나죠?

**Comment by khw7096** [comment]
한국영화를 할 때는 일반적으로 1개이니  잘 쓸것 같아요.
복잡한 중국영화를 할 때는 결국 여러개 설정이 가능한 json같은 자료구조를 이용해서 lut를 여러개 설정할 수 있는 구조를 만들것 같아요.

**Comment by kybin** [comment]
제가 이해한 것이 맞나요?

LUT는 스캔 소스 마다 하나씩 있어야 가장 정확하다.
한국은 일반적으로 프로젝트당 하나의 LUT를 사용한다. (즉, 한 종류의 카메라를 사용한다?)
중국은 시퀀스마다 다른 LUT를 사용하는 경우도 있다.

**Comment by kybin** [comment]
ccc라는 일종의 LUT을 사용하면 그 안에 여러 LUT를 적용해서 사용할수 있다고 함.

또 exr 파일 안에 LUT 정보를 넣는것도 가능

**Comment by khw7096** [comment]
한국이라고 한 종류의 카메라만 사용하는건 아니예요. 여러 di실을 거치지 않아서 di실 편의상 하나의 lut로 가려는 성향이 있을뿐이예요.

**Comment by khw7096** [comment]
인풋 lut 대신 view Lut 라는 용어를 사용해요.

**Comment by kybin** [comment]
아, View LUT 이군요. 고마워요.
