### ISSUE TITLE
제안: 프로젝트, 샷, 태스크 모두 고유 명칭 필드 이름을 ID로 통일

### ISSUE THREAD

**Issue by kybin** [studio2l/roi#92]
고유 명칭이란 테이블 내에서 해당 열을 찾을 수 있도록 다른 값들과 겹치지 않고 유일한 값을 가져야 하는 항목을 이야기 합니다. 

현재 
프로젝트의 고유 명칭은 Code 입니다.
씬의 고유 명칭은 Name 입니다.
태스크에는 아직 고유 명칭이 없습니다.
유저의 고유 명칭은 ID입니다.

이를 모두 ID라는 이름으로 변경할 생각입니다.

기존에도 ID라는 이름을 쓰고 싶었지만 모든 테이블에 id라는 값이 이미 존재하고 있어서 사용하지 못하였습니다. 하지만 이 id를 실제로 부를 일은 거의 없기 때문에, 이를 uniqid 라는 이름으로 바꿀 예정입니다.

어떻게 생각하시나요?

**Comment by kaycho** [comment]
동일하게 ID라고 하면 구분은 어떤 형태로 할실지 궁금합니다.

**Comment by khw7096** [comment]
+2 opio 와 같은 구조라서 맘에 듭니다.

**Comment by kaycho** [comment]
이해했습니다 +2
