### ISSUE TITLE
Output, Review 스트럭트와 테이블 추가

### ISSUE THREAD

**Issue by kybin** [studio2l/roi#94]
저는 로이같은 프로젝트 매니징 툴에서 제일 중요한 요소는 버전 관리라고 생각합니다.
아직 로이에는 버전 관리를 할 수 있는 형식이 존재하지 않습니다.

그래서 Output과 Review를 추가하길 제안합니다. 

아래는 지금까지의 제 생각을 적은 것이고 이를 토대로 더 토론해 보고자 합니다.

Output은 샷 또는 태스크의 아웃풋을 의미하고 버전을 가집니다.
만일 Task 항목이 비어있다면 샷의  아웃풋을 의미합니다.

```
// Output은 샷 또는 태스크의 결과물 중 하나이다. 결과물은 버전을 가지며,
// 이 결과물을 감독 또는 슈퍼바이저가 컨펌하게 된다.
type Output struct {
    ID string <= Shot.ID + "_" + Task.Name + "_" + str(Version)
    Project string <= Project.ID
    Shot string <= Shot.ID
    Task string <= Task.Name // 비어있을 수 있음
    Version int
    File string
    Mov string
    Time Time.Time
}
```

Review는 특정 아웃풋 버전에 대한 리뷰입니다. 주로 슈퍼바이저와 감독의 요구를 담습니다.
만일 Task 항목이 비어있다면 샷의  아웃풋에 대한 리뷰를 의미합니다.

```
// Review는 특정 작업 결과물에 대한 리뷰이다. 특정 버전에 대한 리뷰이며, 
// 아티스트는 이 리뷰에서 나온 지침을 토대로 새 버전을 만들게 된다.
type Review struct {
    ID string <= Shot.ID + "_" + Task.Name + "_" + str(Version) + "_" + r + "_" + str(Review.Num)
    Project string <= Project.ID
    Shot string <= Shot.ID
    Task string <= Task.Name // 비어있을 수 있음
    Version int
    Num int
    Reviewer string <= user.ID
    Comment string
    Time Time.Time
}
```

어떻게 생각하시나요?

**Comment by kybin** [comment]
Review를 Comment로 바꾸는게 나을수 있겠다는 생각이 듭니다. 
리뷰가 무거운 느낌도 있고, 또한 리뷰용 작업과 헷갈린 분도 있습니다.
또 키를 만들때 쓰는 문자 r이 리비전의 r로 착각할 여지가 있다고 보여집니다.

**Comment by kaycho** [comment]
리뷰에는 종류(팀장, 슈퍼바이저, 감독) 가 있어서 별도로 구분하고 그대로 리뷰라는 단어를 쓰는게 명확할것 같습니다. 그리고 코멘트(피드백)는 리뷰시 발생되는 개념이라 의미가 잘 맞지 않는 듯합니다.
참고로 코멘트 없이 상태만 승인으로 변경되야 하는 경우도 있습니다.

**Comment by kybin** [comment]
리뷰는 프로세스이고 코멘트는 그 결과물에 가깝다고 느껴지는데, 
제가 원래 의도한 건 리뷰의 결과물입니다.

> 참고로 코멘트 없이 상태만 승인으로 변경되야 하는 경우도 있습니다.

반대로 승인 여부와 관련없이 코멘트만 작성하는 경우도 있을 것 같습니다.

이 둘이 함께 있다면 리뷰가 더 어울리는 단어지만, 따로 있다면 코멘트가 더 나은 선택일 수 도 있다고 생각합니다.

다만 어떤 것이든 저는 크게 상관은 없습니다. 경식씨의 의견이 확고하다면 다시 리뷰를 사용하는 걸로 하겠습니다.

**Comment by kybin** [comment]
아이디의 샷, 태스크, 아웃풋 구분자를 "." 으로 변경할 생각입니다. "_"는 CG_0010 처럼 각 항목 안에서의 구분에 사용할 예정입니다.

**Comment by kaycho** [comment]
output

1. 사용하신 output의 개념이 잘 이해가 되지 않습니다. 

2. 아래와 같은 흐름은 어떤지 봐주셨으면 합니다.
Assign > 작업요청사항 확인 > shot_task_v001 생성 후 작업 > 작업 완료 > 리뷰 > 피드백 > shot_task_v002 생성 후 작업 ... 

3. 생각하시는 output은 하나의 버전 작업 완료시 output을 생성하게 되는건가요? 


Review와 Comment

1. 설명을 보니 리뷰에서 발생하는 코멘트(피드백)에 대한 struct로 다시 이해했습니다. 다만 코멘트가 아닌 다른 용어를 사용하는게 좋겠습니다. 제작방향에 대한 권한이 있는 담당자에게 요구사항을 전달 받는 상황인데 코멘트는 의견에 가까운 뉘앙스라는 생각이 듭니다. 어떻게 생각하세요? 저도 무엇을 사용하든 크게 상관없고 다른 의견을 존중합니다.

2. 코멘트만 작성해야 한다면 다른 방식으로 (예 : CG Description란에 작성) 접근해야 합니다.
리뷰 후 결정사항은 명확하게 승인, 재작업 등의 상태 변경이 있어야 합니다. 

3. 이미지 피드백을 첨부 할 수 있으면 합니다.

*task가 없는 경우는 어떤 경우인지 좀더 설명 부탁드려요.

**Comment by kybin** [comment]
아웃풋은 버전별 아웃풋이 맞습니다. 흐름도 경식씨가 생각하시는 그 흐름이구요. 아티스트가 작업을 통해 버전을 올렸을 경우 그와 관계되는 정보를 담으려는 것입니다. 

코멘트는 리뷰로 되돌리는 방향으로 생각하겠습니다. 당연히 리뷰와 함께 상태 수정이 있어야 합니다만 상태는 태스크에서 관리하고 있기 때문에 태스크 정보를 수정해주면 된다고 생각합니다.
이미지의 경우는 리뷰 메시지에 html을 사용할수 있게 해주면 되지 않을까요?

제가 제안한 Output은 해당버전 작업 정보로서 리뷰에 도움이 되기 위해 만드는 것이고 Review는 리뷰 내용이 담겨 새 버전의 작업에 도움이 되기 위해 만드는 것이라는 걸 말씀드리고 싶습니다.

**Comment by kaycho** [comment]
이해했습니다!
이미지 피드백 별도 이슈로 이야기하겠습니다.

**Comment by kaycho** [comment]
Task 이해했습니다. 전체에 전달하는 경우 all(혹은 global) 을 선택할 수 있으면 명확할것 같습니다.
